# docker compose -p "contoso-pay" -f C:/workspace/repos/labs/contoso/contoso-pay/backend/docker-compose.yml up -d
services:

  postgres:
    image: postgres:18-alpine
    container_name: contosopay_postgres
    environment:
      POSTGRES_PASSWORD: pass@word1
    ports:
      - "5333:5432"
    volumes:
      - ./scripts/postgresql:/docker-entrypoint-initdb.d
      - contosopay_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 0s
    networks:
      - contosopay_network

  mongodb:
    image: mongo:8
    container_name: contosopay_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass@word
    ports:
      - "27017:27017"
    volumes:
      - ./scripts/mongodb:/docker-entrypoint-initdb.d:ro
      - contosopay_mongodb_data:/data/db
    networks:
      - contosopay_network

volumes:
  contosopay_postgres_data:
    name: contosopay_postgres_data
  contosopay_mongodb_data:
    name: contosopay_mongodb_data

networks:
  contosopay_network:
    name: contosopay_network
    driver: bridge